# Generated by Django 4.1.5 on 2023-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.FloatField()),
                ('count', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
